name: dev env
on:
  push:

jobs:
  create-sentry-release:
    name: Create Sentry release
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Create Sentry release
        uses: getsentry/action-release@v1
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          SENTRY_ORG: ${{ secrets.SENTRY_ORG }}
          SENTRY_PROJECT: ${{ secrets.SENTRY_PROJECT }}
        with:
          environment: production
      - name: Wait and create error
        env:
          SENTRY_DSN: ${{ secrets.SENTRY_DSN }}
        run: |
          curl -sL https://sentry.io/get-cli/ | bash
          sleep 3
          sentry-cli send-event -m $(date)